### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by sp1thas** [OdysLam/odyslam.github.io#1]
Very nice website but cross-site scripting is an issue :/
Prof of concept

![](http://i.imgur.com/Tx7QfPj.gif)

[here](https://stackoverflow.com/questions/20855482/preventing-html-and-script-injections-in-javascript) is a possible solution

**Comment by odyslam** [comment]
Hey,

Thank you so much, I am totally new to web and I always was curious about how injection works. Will fix it asap.

Btw, how did you find this repo?

Cheers^_^

**Comment by sp1thas** [comment]
You had posted something relative on [this](https://www.facebook.com/groups/greek.developers/) facebook group.

greetings!
